- name: Run Security Scan
  id: security_scan
  run: |
    echo "Running Bandit..."
    bandit -r . -f txt -o bandit-results.txt || true

    echo "Running Safety..."
    if [ -f "requirements.txt" ]; then
      safety check -r requirements.txt --output text > safety-results.txt || true
    fi

    echo "Combining Results..."
    echo "🔒 Security Scan Results" > security-scan-results.txt
    echo "=========================" >> security-scan-results.txt
    echo "" >> security-scan-results.txt

    echo "Bandit Scan Results:" >> security-scan-results.txt
    echo "-------------------" >> security-scan-results.txt
    cat bandit-results.txt >> security-scan-results.txt

    echo "" >> security-scan-results.txt
    echo "Dependency Check Results (Safety):" >> security-scan-results.txt
    echo "-------------------------" >> security-scan-results.txt
    cat safety-results.txt >> security-scan-results.txt

    if grep -iE "Severity: High|Severity: Critical" bandit-results.txt > /dev/null 2>&1; then
      echo "vulnerabilities_found=true" >> $GITHUB_OUTPUT
    elif grep -iE "CRITICAL|HIGH" safety-results.txt > /dev/null 2>&1; then
      echo "vulnerabilities_found=true" >> $GITHUB_OUTPUT
    else
      echo "vulnerabilities_found=false" >> $GITHUB_OUTPUT
    fi
